### ISSUE TITLE
用vue/cli@3.x建立的typescript项目，无法完成构建

### ISSUE THREAD

**Issue by Roachard** [didi/mand-mobile#162]
#### **Mand Mobile Version**

1.5.0

#### **OS Version & Browser Version**

win10 chrome67

#### **Node Version, Package Management Tool**

npm 6.1.0
node 10.7.0

#### **Recurring Links**

抱歉，之前没能在CodeSandebox上配置成功，只能给github仓库了
https://github.com/qidaneix/mand-mobile-issue
Tag:  typescript-config-issue

#### **Recurring Steps**

用vue/cli@3.x建立的typescript项目，按照教程配置的vue.config.js，`npm run serve`没问题，但无法完成`npm run build` 报错如下：
![prob](https://user-images.githubusercontent.com/5287990/43175555-576dcd2e-8ff2-11e8-957a-9fedea838008.png)

vue.config.js配置如下：
```javascript
const path = require('path')

const resolve = file => path.resolve(__dirname, file)

module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          loader: 'ts-loader',
          options: {
            appendTsSuffixTo: [/\.vue$/],
            transpileOnly: true,
            getCustomTransformers: () => ({
              before: [
                require('ts-import-plugin')({
                  libraryName: 'mand-mobile',
                  libraryDirectory: 'lib-vw',
                })
              ]
            })
          }
        }
      ]
    }
  }
};

```

#### **Expectant Behaviors**

能正常完成构建。

#### **Actual Behaviors**

构建失败，log如下：

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mand-mobile-issue@0.1.0~prebuild: mand-mobile-issue@0.1.0
6 info lifecycle mand-mobile-issue@0.1.0~build: mand-mobile-issue@0.1.0
7 verbose lifecycle mand-mobile-issue@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle mand-mobile-issue@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\WorkPlace\mand-prob\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Tools\Git\cmd;C:\Users\Roachard\AppData\Local\Microsoft\WindowsApps;C:\Users\Roachard\AppData\Roaming\npm;;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle mand-mobile-issue@0.1.0~build: CWD: C:\WorkPlace\mand-prob
10 silly lifecycle mand-mobile-issue@0.1.0~build: Args: [ '/d /s /c', 'vue-cli-service build' ]
11 silly lifecycle mand-mobile-issue@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle mand-mobile-issue@0.1.0~build: Failed to exec build script
13 verbose stack Error: mand-mobile-issue@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid mand-mobile-issue@0.1.0
15 verbose cwd C:\WorkPlace\mand-prob
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error mand-mobile-issue@0.1.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the mand-mobile-issue@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by xxyan0205** [comment]
是mand-mobile构建的问题么?

**Comment by Roachard** [comment]
@xxyan0205 是的，如果将vue.config.js改为：
```javascript
const path = require('path')

const resolve = file => path.resolve(__dirname, file)

module.exports = {
  configureWebpack: {
    module: {
      rules: [ ]
    }
  }
};
```
就可以顺利打包。
这个工程已经尽可能精简到最小可运行状态了，应该就是ts-loader引入mand-mobile过程中发生的问题。

**Comment by xxyan0205** [comment]
不是mand-mobile的问题

```
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('ts')
      .use('ts-loader')
        .loader('ts-loader')
          .tap(options => {
            options.appendTsSuffixTo = [/\.vue$/]
            options.transpileOnly = true
            options.getCustomTransformers = () => ({
              before: [
                require('ts-import-plugin')({
                  "libraryName": "mand-mobile",
                  "libraryDirectory": 'lib-vw'
                })
              ]
            })
            return options
          })
  }
}
```

**Comment by Roachard** [comment]
@xxyan0205 使用这种方式配置以后可以正常打包了，感谢帮助！

**Comment by Roachard** [comment]
使用了前面回答中的配置方法后可以正常打包了，但打包结果的css中不包含组件样式（在npm run serve下组件样式可以被正常显示的）。
```vue
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <md-button type="primary">TEST BUTTON</md-button>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Button } from 'mand-mobile';
@Component({
  components: {
    [Button.name]: Button,
  },
})
export default class App extends Vue {}
</script>
```

打包后，css文件只有一个app.XXXXXXX.css（为了方便查看，已经格式化过）：
```css
#app {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  color: #2c3e50;
  font-family: Avenir, Helvetica, Arial, sans-serif;
  margin-top: 60px;
  text-align: center
}

/*# sourceMappingURL=app.6fa5d04c.css.map */
```
可以看到，其中并不包含`Button`组件中的`md-button`等样式。

[演示工程 (https://github.com/qidaneix/mand-mobile-issue)](https://github.com/qidaneix/mand-mobile-issue)
Tag: `css-build-issue`

请问这种情况该怎么解决呢？谢谢。

**Comment by xxyan0205** [comment]
不用ts-loader做按需加载，换成babel-loader，https://github.com/mand-mobile/vue-cli3-example/tree/typescript
