### ISSUE TITLE
cannot perform font-heading-large * 2

### ISSUE THREAD

**Issue by snowdream** [didi/mand-mobile#46]
> mand-mobile version/项目版本
1.0.8

> os version & browser version/操作系统版本&浏览器版本
macos . 10.13.4

> node version, package management tool(such as npm/cnpm/yarn) & version for building errors/Node版本，包管理工具(npm/cnpm/yarn等)及版本(如果是构建异常)
 node -v
v8.11.1

 npm -v
5.6.0

> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)
https://didi.github.io/mand-mobile/#/docs/components/form/number-keyboard

引用基本键盘，编译出错。
错误提示如下：
```
Failed to compile.

./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-469af010","scoped":true,"hasInlineConfig":false}!./node_modules/stylus-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/HelloWorld.vue
Module build failed: Error: helloworld/src/components/HelloWorld.vue:53:36
   49|     top 30%
   50|     left 50%
   51|     z-index 9999
   52|     transform translate(-50%, -50%)
   53|     font-size font-heading-large * 2
------------------------------------------^
   54|     text-shadow 0 4px 20px color-text-minor
   55| </style>
   56| 

cannot perform font-heading-large * 2
    at ".md-example-display" (helloworld/src/components/HelloWorld.vue:2:1)

    at Ident.operate (helloworld/node_modules/stylus/lib/nodes/node.js:234:15)
    at Ident.operate (helloworld/node_modules/stylus/lib/nodes/ident.js:155:33)
    at CachedPathEvaluator.Evaluator.visitBinOp (helloworld/node_modules/stylus/lib/visitor/evaluator.js:581:28)
    at CachedPathEvaluator.Visitor.visit (helloworld/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (helloworld/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitExpression (helloworld/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at CachedPathEvaluator.Visitor.visit (helloworld/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (helloworld/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitExpression (helloworld/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at CachedPathEvaluator.Visitor.visit (helloworld/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (helloworld/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitProperty (helloworld/node_modules/stylus/lib/visitor/evaluator.js:687:22)
    at CachedPathEvaluator.Visitor.visit (helloworld/node_modules/stylus/lib/visitor/index.js:28:40)
    at CachedPathEvaluator.Evaluator.visit (helloworld/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at CachedPathEvaluator.Evaluator.visitBlock (helloworld/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at CachedPathEvaluator.Visitor.visit (helloworld/node_modules/stylus/lib/visitor/index.js:28:40)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-469af010","scoped":true,"hasInlineConfig":false}!./node_modules/stylus-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/components/HelloWorld.vue 4:14-374 13:3-17:5 14:22-382
 @ ./src/components/HelloWorld.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```
> recurring steps/复现步骤

> expectant behaviors/期待行为
正常编译

> actual behaviors/实际行为
编译错误

**Comment by lucker2046** [comment]
@moyus @snowdream 
这个问题是因为 `font-heading-large`是我们开发过程中定义的stylus变量，你可以在`@mand-mobile/lib/_style/mixin/theme.styl`中找到这些变量，并在你自身的工程中通过css和stylus的相关配置使用他，我们后续会把这个组件的demo进行修正，避免这样的误会再次发生
